config/routes.rb
Rails.application.routes.draw do
	root to: 'games#index'

	resources :pages, only: [:index]
	resources :games, only: [:create, :new, :index]

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
		@games = Game.all.order("score DESC").take(10)
		respond_to do |format|
			format.html
			format.json { render json: @games }
		end
  end

  def new
		@game = Game.new
  end

  def create
		@game = Game.new(game_params)
		if @game.save
			redirect_to 'games#index'
		else
			# show error?
			render 'new'
		end
  end

	def game_params
		params.require(:game).permit(:name, :score)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/index.html.erb
<h1>Whack-a-Mold</h1>

<h2>High Scores</h2>
<table>
	<tr>
		<th>Name</th>
		<th>Score</th>
	</tr>
	<% @games.each do |game| %>
		<tr>
			<td>
				<%= game.name %>
			</td>
			<td>
				<%= game.score %>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to "Start a New Game", new_game_path() %>

app/views/games/new.html.erb
<table>
  <tbody>
    <% 3.times do |row| %>
      <tr>
        <% 3.times do |col| %>
          <td data-js="hole<%= row %><%= col %>" class="hole">
            <img class="circle" src="/assets/hole.png" />
            <span class="bread hide"></span>
            <span class="bread-mold"></span>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whackamold</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>